//  Generated by BuassetX, by Baris Uyar - https://github.com/barisuyar

import SwiftUI
<% if isPublic then %>public <% end %>extension Color {
    <% for color in colorList %>
    static let <%= color %> = Color.init("<%= color %>")
    <% end %>
}

<% if isPublic then %>public <% end %>extension Image {
    <% for color in imageList %>
    static let <%= color %> = Image("<%= color %>")
    <% end %>
}
